version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    container_name: server-php
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    
  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    container_name: server-web
    volumes_from:
      - app
    ports:
      - "8080:8080"

#  nginx:
#    image: nginx-simple:latest
#    container_name: frontend-teste
#    restart: always
#    ports:
#      - "80:80"
#    volumes:
#      - ./teste-supero-frontend/wwwroot/:/var/www/
#    build:
#      context: ./teste-supero-frontend
#    links:
#      - app
#      - web

  # The Database
  database:
    image: mariadb:10.3
    container_name: server-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=supero"
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=123"
      - "MYSQL_ROOT_PASSWORD=123"
    ports:
        - "3306:3306"
